import type { Metadata } from 'next'
import './styles/globals.css'
import '@radix-ui/themes/styles.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function App({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="kr">
            <body className={`font-inter bg-background antialiased`}>{children}</body>
        </html>
    )
}
